version: '3.5'

# SOLR default port: 8983

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx/conf
        target: /etc/nginx/conf.d/
      - type: bind
        source: ./app/static/
        target: /www/data/ 
    networks:
      - nginxnet

  solr:
    image: solr:7.4.0-alpine
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - type: bind
        source: ./solr/conf
        target: /opt/dictionary/conf
#      - type: volume
#        source: solr
#        target: /opt/solr/server/solr/mycores
    networks:
      - solrnet
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - dictionary
      - /opt/dictionary

  autocomplete:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: autocomplete
    environment:
      - NODE_ENV=production
    ports:
      - "8000:8000"
    networks:
      - solrnet
      - nginxnet

# create a solr network
networks:
  solrnet:
    name: solrnet
  nginxnet:
    name: nginxnet

# create a solr volume
#volumes:
#  solr:

